# Site settings

title: "
author:
  name: "María Azuela Mac Donald & Allen Wagley"
  email: "elcorreodemar@aqui.com ; allen.wagley@comunidad.unam.mx"
description:  "Sitio web con algunas cartas de Margaret Cavendish codificadas con TEI"
